# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/"
  to = "/manifest.m3u8"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"